### ISSUE TITLE
Not sure how to implement a common SJR pattern w/ Opal

### ISSUE THREAD

**Issue by kofno** [opal/opal-rails#54]
This is a fairly common pattern in (my) rails apps, but I'm not sure how to implement it in Opal:

https://gist.github.com/kofno/2762bcc615ce7440b7f0

**Comment by elia** [comment]
Closing with: https://gist.github.com/kofno/2762bcc615ce7440b7f0#comment-1472177

@kofno please let me know / reopen if it's still an issue, thanks!


_from https://gist.github.com/kofno/2762bcc615ce7440b7f0#comment-1472177_

---

@kofno if you assign the rendered template to an instance variable you should be able to get it in the template, eg.:


```rb
# controller

def new
  @form_html = render(partial: 'form')
end
```

```rb
# template
Element.expose :modal
 
the_modal = Element['#the-modal']
the_modal.html = @form_html
the_modal.modal :show
```

You can't mix server side code like `render` into an opal template because it's executed in the client. In fact you can only pass json compatible values to instance variables (string, number etc. are ok, an object is not).
