### ISSUE TITLE
Should sprockets dependency be updated to use >3.0

### ISSUE THREAD

**Issue by classyPimp** [opal/opal-rails#82]
With latest rails releases many gems depend on sprockets >3.0.4 which causes conflicts. Should dep be set to allow sprockets >3.0 without breaking things?

**Comment by raysegantii** [comment]
Isn't sprockets-rails 2.3.3 already allowed sprockets ~> 3.0 ?
`s.add_dependency 'sprockets-rails',     '< 3.0'`

**Comment by classyPimp** [comment]
The problem is that I can't use latest Opal versions with opal-rails. If in gemfile I specify e.g. opal 9.2 dependency incompatibility occurs. Without specifying Opal version, opal-rails automatically uses Opal v 8.1.
Also when I try to use opal-rails with Rails 4.2.6 - it just can't bundle.

**Comment by mibamur** [comment]
Sprockets -> big question
moved to https://github.com/opal/opal-rails/issues/82
@elia close this

**Comment by mibamur** [comment]
@ajjahn can you send me gitter discuss link?

## this gem worked better with Sprocket 2
https://github.com/danielpclark/faster_path

> last production projects worked well

**Comment by dougo** [comment]
Leaving this here in case anyone else runs into it:

Rails 5 [removed the config settings](https://github.com/rails/rails/commit/722227a6f63b0a2fc45bd150a0dd6de3b7878c46) for `assets.digest` and `assets.raise_runtime_errors`, because they now both default to `true` in sprockets-rails 3.0. This means that if you're using Rails 5 you'll probably want to add these config settings to your `config/initializers/assets.rb` until opal-rails starts using sprockets-rails 3.0:
```
# Asset digests allow you to set far-future HTTP expiration dates on all assets,
# yet still be able to expire them through the digest params.
Rails.application.config.assets.digest = true

# Adds additional error checking when serving assets at runtime.
# Checks for improperly declared sprockets dependencies.
# Raises helpful error messages.
Rails.application.config.assets.raise_runtime_errors = true
```

**Comment by elia** [comment]
Should be fixed on master

- 7855b9b947 (Add support for sprockets-rails v3)
